fn main() {
    println!("Project euler problem 2");
    println!("Even Fibonacci numbers");
    println!("Each new term in the Fibonacci sequence is generated by adding the previous two terms. \
    By starting with 1 and 2, the first 10 terms will be: \
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... \
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, \
    find the sum of the even-valued terms.");

    let max_range = 4000000;
    let mut prev = 1;
    let mut next = 1;
    let mut curr;

    let mut sum = 0;
    loop {
        curr = prev + next;
        prev = next;
        next = curr;

        if curr <= max_range
        {
            if curr % 2 == 0
            {
                sum = sum + next;
            }
        }
        else {
            break;
        }  
    }

    println!("Sum is : {}", sum);
}
